# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/66af8d90-4bbb-40c6-bcb1-4b7979f50f64";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2649-DB64";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
 
  fileSystems."/atlantis" =
    { device = "/dev/disk/by-uuid/4C0E02570E023A8A";
      fsType = "ntfs";
      options = [ "rw" "uid=hotdog" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7604ab10-3018-44d0-83b0-ce61279bdbc5"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
